"""added rankings relationship 02

Revision ID: cbf09c7f907f
Revises: 9e3212935023
Create Date: 2026-02-28 21:47:24.963764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cbf09c7f907f'
down_revision: Union[str, Sequence[str], None] = '9e3212935023'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ranking_entries',
    sa.Column('edition_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='Foreign key to the ranking edition'),
    sa.Column('pizzeria_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='Foreign key to the pizzeria'),
    sa.Column('position', sa.Integer(), nullable=False, comment='Position of the pizza in the ranking'),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True, precision=0).with_variant(sa.DateTime(timezone=True), 'sqlite'), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True, precision=0).with_variant(sa.DateTime(timezone=True), 'sqlite'), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['edition_id'], ['api_v1.ranking_editions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pizzeria_id'], ['api_v1.pizzerias.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='api_v1'
    )
    op.alter_column('locations', 'adress',
               existing_type=sa.VARCHAR(length=250),
               comment='',
               existing_nullable=True,
               schema='api_v1')
    op.alter_column('locations', 'city',
               existing_type=sa.VARCHAR(length=50),
               comment='',
               existing_nullable=True,
               schema='api_v1')
    op.alter_column('locations', 'country',
               existing_type=sa.VARCHAR(length=50),
               comment='',
               existing_nullable=True,
               schema='api_v1')
    op.alter_column('locations', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='',
               existing_nullable=True,
               schema='api_v1')
    op.alter_column('locations', 'longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='',
               existing_nullable=True,
               schema='api_v1')
    op.alter_column('locations', 'phone',
               existing_type=sa.VARCHAR(length=20),
               comment='',
               existing_nullable=True,
               schema='api_v1')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('locations', 'phone',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='',
               existing_nullable=True,
               schema='api_v1')
    op.alter_column('locations', 'longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='',
               existing_nullable=True,
               schema='api_v1')
    op.alter_column('locations', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='',
               existing_nullable=True,
               schema='api_v1')
    op.alter_column('locations', 'country',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='',
               existing_nullable=True,
               schema='api_v1')
    op.alter_column('locations', 'city',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='',
               existing_nullable=True,
               schema='api_v1')
    op.alter_column('locations', 'adress',
               existing_type=sa.VARCHAR(length=250),
               comment=None,
               existing_comment='',
               existing_nullable=True,
               schema='api_v1')
    op.drop_table('ranking_entries', schema='api_v1')
    # ### end Alembic commands ###
