"""initial revision 01

Revision ID: 2877bb3dfb26
Revises:
Create Date: 2026-04-27 13:10:28.893046

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2877bb3dfb26"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column(
            "name",
            sa.String(length=50),
            nullable=False,
            comment="Name of the pizza category",
        ),
        sa.Column(
            "description",
            sa.String(length=500),
            nullable=True,
            comment="Description of the pizza category",
        ),
        sa.Column(
            "slug",
            sa.String(length=50),
            nullable=False,
            comment="URL-friendly slug for the pizza category",
        ),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            sa.Identity(
                always=True,
                start=1,
                increment=1,
                minvalue=1,
                maxvalue=9223372036854775807,
                cycle=False,
                cache=1,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True, precision=0).with_variant(
                sa.DateTime(timezone=True), "sqlite"
            ),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True, precision=0).with_variant(
                sa.DateTime(timezone=True), "sqlite"
            ),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug", name="uq_category_slug"),
        schema="api_v1",
    )
    op.create_table(
        "pizzerias",
        sa.Column(
            "name",
            sa.String(length=100),
            nullable=False,
            comment="Name of the pizzeria",
        ),
        sa.Column(
            "description",
            sa.String(length=500),
            nullable=True,
            comment="Description of the pizzeria",
        ),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            sa.Identity(
                always=True,
                start=1,
                increment=1,
                minvalue=1,
                maxvalue=9223372036854775807,
                cycle=False,
                cache=1,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True, precision=0).with_variant(
                sa.DateTime(timezone=True), "sqlite"
            ),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True, precision=0).with_variant(
                sa.DateTime(timezone=True), "sqlite"
            ),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", name="uq_pizzeria_name"),
        schema="api_v1",
    )
    op.create_table(
        "editions",
        sa.Column(
            "category_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
            comment="Foreign key to the categories table",
        ),
        sa.Column(
            "year",
            sa.SmallInteger(),
            nullable=False,
            comment="Year of the ranked edition",
        ),
        sa.Column(
            "url",
            sa.String(length=500),
            nullable=False,
            comment="Endpoint URL for the ranked edition data",
        ),
        sa.Column(
            "scraped_at",
            postgresql.TIMESTAMP(timezone=True, precision=0).with_variant(
                sa.DateTime(timezone=True), "sqlite"
            ),
            nullable=True,
            comment="Timestamp when the data was scraped",
        ),
        sa.Column(
            "parsed_at",
            postgresql.TIMESTAMP(timezone=True, precision=0).with_variant(
                sa.DateTime(timezone=True), "sqlite"
            ),
            nullable=True,
            comment="Timestamp when the data was parsed",
        ),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            sa.Identity(
                always=True,
                start=1,
                increment=1,
                minvalue=1,
                maxvalue=9223372036854775807,
                cycle=False,
                cache=1,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True, precision=0).with_variant(
                sa.DateTime(timezone=True), "sqlite"
            ),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True, precision=0).with_variant(
                sa.DateTime(timezone=True), "sqlite"
            ),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["category_id"], ["api_v1.categories.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "category_id", "year", name="uq_ranking_edition_category_year"
        ),
        sa.UniqueConstraint("url", name="uq_ranking_edition_url"),
        schema="api_v1",
    )
    op.create_table(
        "locations",
        sa.Column(
            "pizzeria_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
            comment="Foreign key to the pizzerias table",
        ),
        sa.Column("adress", sa.String(length=250), nullable=True),
        sa.Column("city", sa.String(length=50), nullable=True),
        sa.Column("country", sa.String(length=50), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            sa.Identity(
                always=True,
                start=1,
                increment=1,
                minvalue=1,
                maxvalue=9223372036854775807,
                cycle=False,
                cache=1,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True, precision=0).with_variant(
                sa.DateTime(timezone=True), "sqlite"
            ),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True, precision=0).with_variant(
                sa.DateTime(timezone=True), "sqlite"
            ),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["pizzeria_id"], ["api_v1.pizzerias.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "pizzeria_id",
            "latitude",
            "longitude",
            name="uq_location_pizzeria_latitude_longitude",
        ),
        schema="api_v1",
    )
    op.create_table(
        "webpages",
        sa.Column(
            "pizzeria_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
            comment="Foreign key to the pizzerias table",
        ),
        sa.Column(
            "url",
            sa.String(length=500),
            nullable=False,
            comment="URL of the pizzeria's page on 50 Top Pizza",
        ),
        sa.Column(
            "slug",
            sa.String(length=200),
            nullable=False,
            comment="URL-friendly slug for the pizzeria",
        ),
        sa.Column(
            "scraped_at",
            postgresql.TIMESTAMP(timezone=True, precision=0).with_variant(
                sa.DateTime(timezone=True), "sqlite"
            ),
            nullable=True,
            comment="Timestamp when the data was scraped",
        ),
        sa.Column(
            "parsed_at",
            postgresql.TIMESTAMP(timezone=True, precision=0).with_variant(
                sa.DateTime(timezone=True), "sqlite"
            ),
            nullable=True,
            comment="Timestamp when the data was parsed",
        ),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            sa.Identity(
                always=True,
                start=1,
                increment=1,
                minvalue=1,
                maxvalue=9223372036854775807,
                cycle=False,
                cache=1,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True, precision=0).with_variant(
                sa.DateTime(timezone=True), "sqlite"
            ),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True, precision=0).with_variant(
                sa.DateTime(timezone=True), "sqlite"
            ),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["pizzeria_id"], ["api_v1.pizzerias.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("pizzeria_id", "url", name="uq_webpage_pizzeria_url"),
        schema="api_v1",
    )
    op.create_table(
        "awards",
        sa.Column(
            "edition_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
            comment="Foreign key to the ranking edition",
        ),
        sa.Column(
            "pizzeria_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
            comment="Foreign key to the pizzeria",
        ),
        sa.Column(
            "award",
            sa.String(length=255),
            nullable=False,
            comment="The award received by the pizzeria",
        ),
        sa.Column(
            "sponsor",
            sa.String(length=200),
            nullable=False,
            comment="Sponsor of the award",
        ),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            sa.Identity(
                always=True,
                start=1,
                increment=1,
                minvalue=1,
                maxvalue=9223372036854775807,
                cycle=False,
                cache=1,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True, precision=0).with_variant(
                sa.DateTime(timezone=True), "sqlite"
            ),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True, precision=0).with_variant(
                sa.DateTime(timezone=True), "sqlite"
            ),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["edition_id"], ["api_v1.editions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["pizzeria_id"], ["api_v1.pizzerias.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "edition_id", "pizzeria_id", name="uq_award_edition_pizzeria"
        ),
        schema="api_v1",
    )
    op.create_table(
        "rankings",
        sa.Column(
            "edition_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
            comment="Foreign key to the ranking edition",
        ),
        sa.Column(
            "pizzeria_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
            comment="Foreign key to the pizzeria",
        ),
        sa.Column(
            "position",
            sa.Integer(),
            nullable=False,
            comment="Position of the pizza in the ranking",
        ),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            sa.Identity(
                always=True,
                start=1,
                increment=1,
                minvalue=1,
                maxvalue=9223372036854775807,
                cycle=False,
                cache=1,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True, precision=0).with_variant(
                sa.DateTime(timezone=True), "sqlite"
            ),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True, precision=0).with_variant(
                sa.DateTime(timezone=True), "sqlite"
            ),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["edition_id"], ["api_v1.editions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["pizzeria_id"], ["api_v1.pizzerias.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "edition_id", "pizzeria_id", name="uq_ranking_entry_edition_pizzeria"
        ),
        schema="api_v1",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("rankings", schema="api_v1")
    op.drop_table("awards", schema="api_v1")
    op.drop_table("webpages", schema="api_v1")
    op.drop_table("locations", schema="api_v1")
    op.drop_table("editions", schema="api_v1")
    op.drop_table("pizzerias", schema="api_v1")
    op.drop_table("categories", schema="api_v1")
    # ### end Alembic commands ###
