"""added_staging_table_for_worker_02

Revision ID: 430b0b82aa95
Revises: 2877bb3dfb26
Create Date: 2026-07-04 16:00:55.857519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '430b0b82aa95'
down_revision: Union[str, Sequence[str], None] = '2877bb3dfb26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payload_staging',
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False, comment='Serialized list[CategorySchema] submitted for ingestion.'),
    sa.Column('status', sa.Enum('pending', 'consumed', 'failed', name='payload_status'), nullable=False, comment='Lifecycle status: pending -> consumed | failed.'),
    sa.Column('consumed_at', postgresql.TIMESTAMP(timezone=True, precision=0).with_variant(sa.DateTime(timezone=True), 'sqlite'), nullable=True, comment='When the worker finished processing this payload.'),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True, precision=0).with_variant(sa.DateTime(timezone=True), 'sqlite'), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True, precision=0).with_variant(sa.DateTime(timezone=True), 'sqlite'), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='api_v1'
    )
    op.alter_column('categories', 'description',
               existing_type=sa.VARCHAR(length=500),
               nullable=False,
               existing_comment='Description of the pizza category',
               schema='api_v1')
    op.alter_column('locations', 'address',
               existing_type=sa.VARCHAR(length=250),
               comment='Pizzeria address',
               existing_nullable=True,
               schema='api_v1')
    op.alter_column('locations', 'city',
               existing_type=sa.VARCHAR(length=50),
               comment='Pizzeria city',
               existing_nullable=True,
               schema='api_v1')
    op.alter_column('locations', 'country',
               existing_type=sa.VARCHAR(length=50),
               comment='Pizzeria country',
               existing_nullable=True,
               schema='api_v1')
    op.alter_column('locations', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Pizzeria latitude',
               existing_nullable=True,
               schema='api_v1')
    op.alter_column('locations', 'longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Pizzeria longitude',
               existing_nullable=True,
               schema='api_v1')
    op.alter_column('locations', 'phone',
               existing_type=sa.VARCHAR(length=20),
               comment='Pizzeria phonenumber',
               existing_nullable=True,
               schema='api_v1')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('locations', 'phone',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Pizzeria phonenumber',
               existing_nullable=True,
               schema='api_v1')
    op.alter_column('locations', 'longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Pizzeria longitude',
               existing_nullable=True,
               schema='api_v1')
    op.alter_column('locations', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Pizzeria latitude',
               existing_nullable=True,
               schema='api_v1')
    op.alter_column('locations', 'country',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Pizzeria country',
               existing_nullable=True,
               schema='api_v1')
    op.alter_column('locations', 'city',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Pizzeria city',
               existing_nullable=True,
               schema='api_v1')
    op.alter_column('locations', 'address',
               existing_type=sa.VARCHAR(length=250),
               comment=None,
               existing_comment='Pizzeria address',
               existing_nullable=True,
               schema='api_v1')
    op.alter_column('categories', 'description',
               existing_type=sa.VARCHAR(length=500),
               nullable=True,
               existing_comment='Description of the pizza category',
               schema='api_v1')
    op.drop_table('payload_staging', schema='api_v1')
    # ### end Alembic commands ###
