"""Added parsed_at columns 03

Revision ID: 852a352efb90
Revises: 92ce288836b7
Create Date: 2026-04-19 10:54:37.451349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '852a352efb90'
down_revision: Union[str, Sequence[str], None] = '92ce288836b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('editions', sa.Column('parsed_at', postgresql.TIMESTAMP(timezone=True, precision=0).with_variant(sa.DateTime(timezone=True), 'sqlite'), nullable=True, comment='Timestamp when the data was parsed'), schema='api_v1')
    op.alter_column('locations', 'adress',
               existing_type=sa.VARCHAR(length=250),
               comment='',
               existing_nullable=True,
               schema='api_v1')
    op.alter_column('locations', 'city',
               existing_type=sa.VARCHAR(length=50),
               comment='',
               existing_nullable=True,
               schema='api_v1')
    op.alter_column('locations', 'country',
               existing_type=sa.VARCHAR(length=50),
               comment='',
               existing_nullable=True,
               schema='api_v1')
    op.alter_column('locations', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='',
               existing_nullable=True,
               schema='api_v1')
    op.alter_column('locations', 'longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='',
               existing_nullable=True,
               schema='api_v1')
    op.alter_column('locations', 'phone',
               existing_type=sa.VARCHAR(length=20),
               comment='',
               existing_nullable=True,
               schema='api_v1')
    op.add_column('webpages', sa.Column('parsed_at', postgresql.TIMESTAMP(timezone=True, precision=0).with_variant(sa.DateTime(timezone=True), 'sqlite'), nullable=True, comment='Timestamp when the data was parsed'), schema='api_v1')
    op.drop_constraint(op.f('uq_webpage_slug'), 'webpages', schema='api_v1', type_='unique')
    op.create_unique_constraint('uq_webpage_pizzeria_url', 'webpages', ['pizzeria_id', 'url'], schema='api_v1')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_webpage_pizzeria_url', 'webpages', schema='api_v1', type_='unique')
    op.create_unique_constraint(op.f('uq_webpage_slug'), 'webpages', ['slug'], schema='api_v1', postgresql_nulls_not_distinct=False)
    op.drop_column('webpages', 'parsed_at', schema='api_v1')
    op.alter_column('locations', 'phone',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='',
               existing_nullable=True,
               schema='api_v1')
    op.alter_column('locations', 'longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='',
               existing_nullable=True,
               schema='api_v1')
    op.alter_column('locations', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='',
               existing_nullable=True,
               schema='api_v1')
    op.alter_column('locations', 'country',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='',
               existing_nullable=True,
               schema='api_v1')
    op.alter_column('locations', 'city',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='',
               existing_nullable=True,
               schema='api_v1')
    op.alter_column('locations', 'adress',
               existing_type=sa.VARCHAR(length=250),
               comment=None,
               existing_comment='',
               existing_nullable=True,
               schema='api_v1')
    op.drop_column('editions', 'parsed_at', schema='api_v1')
    # ### end Alembic commands ###
